### ISSUE TITLE
开放平台图标

### ISSUE THREAD

**Issue by heavyrain2012** [wildfirechat/open-platform#3]
1. 开放平台支持上传图片，不要使用图片地址
2. 如果没有上次应用icon，默认icon是如何处理？work页面检查为空时显示默认头像？

**Comment by zhang-ykun** [comment]
上传图片不还是地址，图片应该有专门的服务器

**Comment by imndx** [comment]
> 上传图片不还是地址，图片应该有专门的服务器

图片会上传到专门的媒体服务器

**Comment by imndx** [comment]
> 1. 开放平台支持上传图片，不要使用图片地址
> 2. 如果没有上次应用icon，默认icon是如何处理？work页面检查为空时显示默认头像？

强制要求上传图标。
