### ISSUE TITLE
open-web和open-work怎么接入到自己的后端没有看见ip地址这一类的

### ISSUE THREAD

**Issue by misunderstand5** [wildfirechat/open-platform#6]
open-web和open-work怎么接入到自己的后端没有看见ip地址这一类的啊。
![image](https://user-images.githubusercontent.com/96658587/224617813-221aead2-2e8d-40f3-b717-e0e5a2ee45d9.png)
open-web首页的登录密码是什么啊？

**Comment by imndx** [comment]
请看下`readme`，默认用户名和密码是：`admin/admin123`，登录成功之后，请尽快修改默认密码

**Comment by imndx** [comment]
`im`管理地址等相关配置请看下`config/application.properties`文件
