### ISSUE TITLE
关于 📂开放平台(open-work) 和 📂日志应用(web) 的 token逻辑再确认，和App.vue中的login方法传参疑问

### ISSUE THREAD

**Issue by carolinetanxin** [wildfirechat/open-platform#7]
### 关于`authToken`的存取逻辑`再确认`和`疑问`

看了 `📂open-work` 和 日志应用`📂web`，都使用了`jssdk`和统一的`inceptor`文件逻辑。想和野火团队做下确认：
① 如果接口传参请求头带了authToken，不会再走`login()`方法，不然就会走`login()`方法获取服务器返回的`authToken`字段。(两个项目的前端文件，该方法是一致的嘛？）

②在查看`App.vue`代码的时候，`getAuthCode`写死了传参，分别是`wfcadmin`和`2`，这个在自行开发的时候需要做修改吗？还是不需要修改直接自行继续开发即可？(如果可以的话希望野火的老师可以完善或指路这一块`authToken`的详细逻辑说明，看代码不确定老师们是如何封装交互逻辑，就让前后端完成了身份验证的。万分感谢
(灬ꈍ ꈍ灬))
<img width="876" alt="image" src="https://github.com/wildfirechat/open-platform/assets/19150785/c9b6ba0f-b418-40d1-b6bc-f1bbc10ccf73">

**Comment by imndx** [comment]
1. 有`authToken`且合法的，服务端会认为已经登录
2. getAuthCode写死了传参，分别是`wfcadmin`和`2`，这两个值是固定写死的，不用修改。

**Comment by carolinetanxin** [comment]
> 1. 有`authToken`且合法的，服务端会认为已经登录
> 2. getAuthCode写死了传参，分别是`wfcadmin`和`2`，这两个值是固定写死的，不用修改。

谢谢老师的回复！所以这个`authToken `的获取、保存交互的实现逻辑是：

> 用户初次登录->打开开放平台->会去走`login()`方法获取存储->后续同账号再次打开开放平台的时候，只要`localStorage`里的`authToken`不被清理，服务端就一直会验证身份通过，不会再次走`login`方法。

是这样理解吧？

**Comment by imndx** [comment]
是的
